# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
commands:
  create_concatenated_package_json:
    description: "Concatenate all package.json files recognized by lerna.js into single file. File is used as checksum source for part of caching key."
    parameters:
      filename:
        type: string
    steps:
      - run:
          name: Combine package.json files to single file
          command: npx lerna list -p -a | awk -F packages '{printf "\"packages%s/package.json\" ", $2}' | xargs cat > << parameters.filename >>
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - create_concatenated_package_json:
          filename: combined-package-json.txt

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "combined-package-json.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npx lerna bootstrap

      - save_cache:
          paths:
            - node_modules
            - packages/less-plugin-dls/node_modules
            - packages/dls-color-palette/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "combined-package-json.txt" }}

      # run tests!
      - run: npm run test
